### PR TITLE
build_fix_non-existing_trezord_branch

### PR DESCRIPTION
**Pull request by marsmensch**
Docker build is currently breaking. This pull request removes non-existing trezord branch from tresor.js deps

### CODE REVIEW

**Comment by micressor** [comment]
+1 building via docker is currently not working.
May be there is more broken now.

**Comment by prusnak** [comment]
This is unmaintained old code of our webwallet. I will merge this pull request, but we won't be working on any other breakages.

**Comment by markburns** [comment]
@prusnak This means your webwallet is closed source?

**Comment by prusnak** [comment]
The source you see in this repository is open-source. It is just not updated to current version we have on production servers. After New Years' we'll have an internal discussion about bringing this repository up to speed.

**Pull request merged**
